# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('choice', models.SmallIntegerField(choices=[(0, 'relax'), (1, 'emergent'), (2, 'superb')], max_length=1)),
                ('DueTime', models.DateTimeField()),
            ],
        ),
    ]
