# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskbuster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='DueTime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
